### ISSUE TITLE
Add `--repair` option to repair databases launched on a data volume restored from snapshot

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-mongodb#26]
* [ ] If `EXPOSE_HOST` and `EXPOSE_PORT` are present, re-initialize the replica set configuration to include just this host:port as a member
* [ ] Call `repairDatabase()` to resolve any index corruption issues

**Comment by krallin** [comment]
- Replica set re-configuration was addressed in #30.
- I think `repairDatabase()` is no longer required since recent MongoDB DBs have journalling enabled.
